# Author: Zbigniew Dynowski
P_CROSSOVER = 0.5
P_MUTATION = 0.5
SPLIT_PROBABILITY = 0.5
POPULATION_SIZE = 50
TOURNAMENT_SIZE = 5
ELITE_SIZE = 2
EXPECTED_TREE_HEIGHT = 10
MAX_ITERATIONS = 500
STALL_ITERATIONS = 100
TRAIN_RATIO = 0.7
ALPHA = 0.99
BETA = 0.01
MAX_TREE_DEPTH = 30
NUM_SPLITS = 5
NUM_REPEATS = 5
